[package]
name = "memory_safety"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
image = "0.25.6"

[profile.release]
opt-level = 3
lto = true
codegen-units = 8
panic = "abort"
strip = true
